apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transfer-shortener-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: transfer-shortener-pv
  resources:
    requests:
      storage: 100Mi
